# Generated by Django 2.2 on 2019-04-16 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TtcRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('title', models.TextField()),
                ('lat_min', models.FloatField()),
                ('lon_min', models.FloatField()),
                ('lat_max', models.FloatField()),
                ('lon_max', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TtcStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('title', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasaver.TtcRoute')),
            ],
        ),
    ]
