# Generated by Django 2.2 on 2019-04-16 15:21
# edited immediately thereafter to add row to table

from django.db import migrations, models

def insert_ttc_routes(apps, schema_editor):
    Lock = apps.get_model('datasaver', 'Lock')
    Lock.objects.create(resource='ttc_routes', locked=False)

class Migration(migrations.Migration):

    dependencies = [
        ('datasaver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.TextField()),
                ('locked', models.BooleanField()),
            ],
        ),
        migrations.RunPython(insert_ttc_routes, migrations.RunPython.noop),
    ]
