# Generated by Django 2.2 on 2019-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasaver', '0002_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='resource',
            field=models.TextField(db_index=True),
        ),
    ]
